server:
  port: 8888

spring:
  datasource:
    name: main
    url: jdbc:mysql://127.0.0.1:3306/db_signin?useUnicode=true&characterEncoding=UTF-8 #&useSSL=false
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

# 该配置节点为独立的节点，放在spring的节点下会导致配置无法被识别
mybatis:
  mapper-locations: classpath:mybatis/*.xml       # 对应mapper映射xml文件的所在路径
  type-aliases-package: club.szuai.signin.bean    # 对应实体类的路径

system-params:
  imageUri: /root/signin