server:
  port: 8888
  ssl:
    key-store: /root/signin/SHA256withRSA_szuai.club.pfx
    key-store-password: 1234
    key-store-type: PKCS12

spring:
  datasource:
    name: main
    url: jdbc:mysql://127.0.0.1:3306/db_signin?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      filters: stat
      max-active: 20
      max-wait: 60000
      min-idle: 1
      validation-query: select 'x'
      max-open-prepared-statements: 20
      pool-prepared-statements: true
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      min-evictable-idle-time-millis: 300000
      time-between-connect-error-millis: 60000

# 该配置节点为独立的节点，放在spring的节点下会导致配置无法被识别
mybatis:
  mapper-locations: classpath:mybatis/*.xml       # 对应mapper映射xml文件的所在路径
  type-aliases-package: club.szuai.signin.bean    # 对应实体类的路径

system-params:
  imageUri: /root/signin